// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTraffic() {
  return window['go']['main']['App']['ClearTraffic']();
}

export function GetRoutes() {
  return window['go']['main']['App']['GetRoutes']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTraffic() {
  return window['go']['main']['App']['GetTraffic']();
}

export function GetTunnelStatus() {
  return window['go']['main']['App']['GetTunnelStatus']();
}

export function RemoveRoute(arg1) {
  return window['go']['main']['App']['RemoveRoute'](arg1);
}

export function StartApp(arg1, arg2) {
  return window['go']['main']['App']['StartApp'](arg1, arg2);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}
