// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';

export function ClearTraffic():Promise<void>;

export function GetRoutes():Promise<Array<Record<string, any>>>;

export function GetStatus():Promise<Record<string, any>>;

export function GetTraffic():Promise<Array<proxy.CaptureEntry>>;

export function GetTunnelStatus():Promise<proxy.TunnelStatus>;

export function RemoveRoute(arg1:string):Promise<void>;

export function StartApp(arg1:string,arg2:string):Promise<string>;

export function StartTunnel(arg1:string):Promise<void>;

export function StopTunnel(arg1:string):Promise<void>;
